### ISSUE TITLE
Arrow-key navigation doesn't work on desktop icons in some cases

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop-view#11]
I think I found the reason, why arrow-key navigation doesn't work on desktop icons in some cases.
You have to add **Home Directory** if you want it to **work after reboot.**
Because after reboot or logout (if you don't have Home Directory icon) arrow-key navigation doesn't work.

tested on Fedora 37

**Comment by JoshStrobl** [comment]
Arrow navigation still works for me when Home Directory is disabled.

**Comment by Solarunit** [comment]
even after reboot?
