### ISSUE TITLE
Touchpad pointer disappears

### ISSUE THREAD

**Issue by GianniJT** [BuddiesOfBudgie/budgie-desktop-view#14]
After installing budgie-desktop-view, my touchpad pointer disappears after I use my touchscreen - this I understand to be normal.  However, the pointer does not re-appear when moving the touchpad or clicking.  It will invisible move as it does highlight menu items but otherwise does not function.  Removal of the module restores normal touchpad functionality.

This is not unique to Manjaro.  As the Budgie desktop is my desktop of choice, I have tried almost every distro that includes it  and it happens in every version; solus, spiralLinux budgie, gecko budgie edition, RebornOS, etc.  I thought at first that this might be a display server or windows management issue.   However, because Manjaro did not automatically install the budgie-desktop-view component when installing the budgie desktop ( after an initial install with XFCE) , I believe I have isolated this component as the cause of the bug.  Right now budgie desktop is installed and working well, but without any desktop icons. Isolation as to the cause of this behavior would benefit every distro using Budgie.

By the way, this bug has been documented by others in other distros and no one has been able to come up with a fix.  There is a workaround if you add a top panel and move the touchpad to the top.

**Comment by JoshStrobl** [comment]
Neither Budgie Desktop nor Budgie Desktop View has explicit support for touch screens. It just happens to function to a degree because of how GTK handles click events.

**Comment by fossfreedom** [comment]
Probably fixed with mutter 43.3

https://gitlab.gnome.org/GNOME/mutter/-/issues/2376

**Comment by GianniJT** [comment]
Thanks David,

  I did see the post that you referenced below , but it doesn’t look like 43.3 is available yet in the Manjaro rep.  When its available I’ll update Mutter and see if that fixes the issue. However, it still seems like there is something specific about the particular component ‘budgie-desktop-view’ that causes the problem as it is totally reproducible. When it is added the problem occurs and the problem disappears when it is removed. It seems to meet the criteria for causation.

Regards,

John
