### ISSUE TITLE
[Bug] Desktop icons are not movable!

### ISSUE THREAD

**Issue by LauraTaylorUK** [BuddiesOfBudgie/budgie-desktop-view#27]
### Description

The Desktop icons can't be moved!

### Budgie version

10.8.2

### Operating System

Fedora Linux 39 (Budgie)

### Steps to reproduce the issue

1. Install Fedora Linux 39 budgie spin (iso image)
2. Budgie Desktop Settings -> Desktop -> Desktop Icons (enable)
3. Create or place some files under ~/Desktop
4. Try to move them with the mouse
5. Confirm that they can't be moved

### Actual result

The Desktop icons can't be moved!

### Expected result

I would expect to move my desktop icons around the desktop surface and place them based on my background image (so the icons don't overlap some areas of the background image).

**Comment by fossfreedom** [comment]
Moving icons within budgie-desktop-view which some distros use out of the box is not available.  That's by design.

Budgie also supports other desktop icon solutions - nemo and desktopfolder.  Obviously you can't run both budgie-desktop-view and another app providing desktop icons.

The gsettings key com.solus-project.budgie-wm desktop-type-override can be updated (use dconf-editor for a GUI method) to change between different implementations that budgie supports.

**Comment by LauraTaylorUK** [comment]
Umm... what an awkward situation.

Would it be possible to create a feature request and have this implemented in the future?

If not, could we have some solution that does not involve hack-ish ways like gsettings?

I'm trying to install Fedora on 200 desktop PCs, I'm between the Budgie spin and the Cinnamon spin, but having a fully working desktop (with real icons, not fake ones) is important to us. We would rather avoid having to hack the default system to add some functionality if that was possible.

Thank you!

**Comment by JoshStrobl** [comment]
> Would it be possible to create a feature request and have this implemented in the future?

I don't have any plans on experimenting with this until I port it to another toolkit and still no guarantee that I'll actually do it then. The current implementation leverages GtkFlowbox and the logic required for arbitrary locations is quite complex and not something I desire in BDV's current form.

> If not, could we have some solution that does not involve hack-ish ways like gsettings?

The gsettings is not a hackish solution, it's an internal option intended for distributors of Budgie Desktop. Upon changing it, assuming the other program is installed, we actually expose several settings that the application does.
