### ISSUE TITLE
Feature Request: Refresh Button

### ISSUE THREAD

**Issue by jake770321** [BuddiesOfBudgie/budgie-desktop-view#3]
Hi,
A restart/logout is currently required to apply any changes made to .desktop files. A refresh option on the right click menu would make creating/modifying .desktop files much easier and more straightforward. As someone fairly new to linux, creating desktop shortcuts is a pain and i feel like a refresh option would help a lot as it took me a frustratingly long amount of time to figure out that changes only apply after logging out or restarting.
Thanks

**Comment by JoshStrobl** [comment]
Seems more like a bug in monitoring of filesystem changes than something which requires a dedicated refresh feature. Can you explain what you were editing on the desktop file that did not propagate to the view? Thanks!

**Comment by jake770321** [comment]
I'm trying to edit a .desktop file using gedit. Any changes i make aren't aren't applied until after i log out and then back in.

**Comment by BlindRepublic** [comment]
I've been trying to reproduce this myself and I have not been successful.
