### ISSUE TITLE
[Request] Nemo can't move files to the desktop

### ISSUE THREAD

**Issue by seriousfreezing** [BuddiesOfBudgie/budgie-desktop-view#30]
### Budgie version

10.9.1

### Use-cases

Why is it that when I cut a file in Nemo it can't be moved to the Desktop?

**Comment by JoshStrobl** [comment]
Move it into the Desktop folder _via_ Nemo. Budgie Desktop View isn't a file manager and doesn't provide those sorts of IO operations.
